let bookitems =[{id: 1, title: "Hunger Games", author: "Suzanne Collins", year: 2010, price: 7.50, sold: 2272, category: 2, image_url: "Images/hungergames.jpg", description: "In a post-apocalyptic future, life has turned extremely hard. Fighting poverty and hunger every day, sixteen years old hunter Katniss does absolutely everything in her power to have enough for her defenseless little sister, and a barely lucid mother. Life is hard, yet not impossible, until the one fateful day arrives."}, 
    {id: 2, title: "2001 A Space Odessey", author: "Arthur C. Clarke", year: 1968, price: 7.75, sold: 9151, category: 1, image_url: "Images/2001-a-space-odyssey.jpg", description: "2001: A Space Odyssey explores technological advancement: its promise and its danger. The HAL 9000 computer puts forward the troubles that can crop up when humans build machines, the inner workings of which are not fully comprehended and therefore cannot fully be controlled."}, 
    {id: 3, title: "Dune", author: "Frank Herbert", year: 1965, price: 8.95, sold: 5581, category: 1, image_url: "Images/dune.jpg", description: "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the “spice” melange, a drug capable of extending life and enhancing consciousness."}, 
    {id: 4, title: "Fareheit 451", author: "Ray Bradbury", year: 1957, price: 5.95, sold: 8290, category: 2, image_url: "Images/farenheit-451.jpg", description: "Fahrenheit 451 tells the story of Guy Montag and his transformation from a book-burning fireman to a book-reading rebel. Montag lives in an oppressive society that attempts to eliminate all sources of complexity, contradiction, and confusion to ensure uncomplicated happiness for all its citizens."}, 
    {id: 5, title: "Foundation", author: "Isaac Asimov", year: 1993, price: 8.50, sold: 6578, category: 1, image_url: "Images/foundation.jpg", description: "Foundation is set in the future, when the world is barely remembered, and humans have colonized the galaxy. The book introduces Hari Seldon, a brilliant visionary and psychohistorian whose job is to use mathematics and probability to predict the future."}, 
    {id: 6, title: "Hitchhikers Guide to the Galaxy", author: "Douglas Adams", year: 2003, price: 8.95, sold: 9263, category: 5, image_url: "Images/hitchhikers-guide-to-the-galaxy-cover.jpg", description: "The broad narrative of Hitchhiker follows the misadventures of the last surviving man, Arthur Dent, following the demolition of the planet Earth by a Vogon constructor fleet to make way for a hyperspace bypass."}, 
    {id: 7, title: "Stranger in a Strange Land", author: "Robert A. Heinlein", year: 1994, price: 6.95, sold: 2265, category: 3, image_url: "Images/Stranger-in-a-Strange-Land-by-Robert-Heinlein.jpg", description: "Valentine Michael Smith is a human being raised on Mars, newly returned to Earth. Among his people for the first time, he struggles to understand the social mores and prejudices of human nature that are so alien to him, while teaching them his own fundamental beliefs in grokking, watersharing, and love."}, 
    {id: 8, title: "1984", author: "George Orwell", year: 2001, price: 10.95, sold: 814, category: 2, image_url: "Images/1984.jpg", description: "1984 is the story of a man questioning the system that keeps his futuristic but dystopian society afloat and the chaos that quickly ensues once he gives in to his natural curiosity and desire to be free."},
    {id: 9, title: "Recursion", author: "Blake Crouch", year: 2019, price: 9.25, sold: 1094, category: 4, image_url: "Images/recursion.jpg", description:"Memory makes reality. That's what NYC cop Barry Sutton is learning, as he investigates the devastating phenomenon the media has dubbed False Memory Syndrome—a mysterious affliction that drives its victims mad with memories of a life they never lived. That's what neuroscientist Helena Smith believes."},
    {id: 10, title: "The Time Machine", author: "H. G. Wells", year: 1895, price: 4.50, sold: 762, category: 4, image_url: "Images/The-time-machine.jpg", description:"A Victorian-era scientist (played by Rod Taylor) invents a machine that transports him through time. He travels forward to flee the warlike world of 1900. He stops the machine in 1917, in 1940, and in 1966, but he finds the world at war on all three occasions."},
    {id: 11, title: "How to Stop Time", author: "Matt Haig", year: 2017, price: 5.90, sold: 530, category: 4, image_url: "Images/How-to-stop-time.jpg", description:"How to Stop Time is a 2017 novel by English author Matt Haig. It follows protagonist Tom Hazard through his 400-year life as he loses himself to fear and seeks purpose. This novel deals with themes concerning the inevitability of change and learning to find happiness."},  
    {id: 12, title: "Do androids dream of Electric Sheep?", author: "Philip K. Dick", year: 1968, price: 11.50, sold: 11024, category: 3, image_url: "Images/Do-androids-dream-of-Electric-Sheep.jpg", description:"The main plot follows Rick Deckard, a bounty hunter who has to 'retire' (i.e. kill) six escaped Nexus-6 model androids, while a secondary plot follows John Isidore, a man of sub-par IQ who aids the fugitive androids."},  
    {id: 13, title: "Ready Player One", author: "Ernest Cline", year: 2011, price:7.53, sold: 10344, category: 3, image_url: "Images/Ready-player-one.jpg", description:"The story, set in a dystopia in 2045, follows protagonist Wade Watts on his search for an Easter egg in a worldwide virtual reality game, the discovery of which would lead him to inherit the game creator's fortune and the game itself."},
    {id: 14, title: "Key Lime Sky", author: "Al Hess", year: 2024, price: 11.05, sold: 5023, category: 5, image_url: "Images/Key-lime-sky.jpg", description:"Key Lime Sky is cosy queer science fiction about a small town being invaded by aliens (possibly). Denver Bryant, a non-binary pie blogger, witnesses a UFO explode over his hometown."}, 
    {id: 15, title: "The World of the Worlds", author: "H. G. Wells", year: 1898, price: 10.32, sold: 3297, category: 5, image_url: "Images/The-world-of-the-worlds.jpg", description:"The War of the Worlds by H.G. Wells is about a fictional invasion of Southern England by Martians. The military is powerless against the Martians' superior weapons, and many people die. The Martians are eventually killed by bacterial infection."}, 
    {id: 16, title: "Hatchet", author: "Gary Paulsen", year: 1987, price: 9.25, sold: 208, category: 9, image_url: "Images/Hatchet.jpg", description:"Hatchet is a young-adult adventure novel about Brian Robeson's survival following a plane crash. The novel explores themes of positive thinking and perseverance as Brian faces challenges from nature, like bears, porcupines, dehydration, and starvation; all with only his trusty hatchet to help him."}, 
    {id: 17, title: "Jurassic Park", author: "Michael Crichton", year: 1990, price: 3.12, sold: 475, category: 6, image_url: "Images/Jurassic-park.jpg", description:"A cautionary tale about genetic engineering, it presents the collapse of a zoological park showcasing genetically recreated dinosaurs to illustrate the mathematical concept of chaos theory and its real-world implications."}, 
    {id: 18, title: "The Da Vinci Code", author: "Dan Brown", year: 2003, price: 5.65, sold: 8709, category: 6, image_url: "Images/The-Da-Vinci-Code.jpg", description:"The Da Vinci Code follows symbologist Langdon and cryptologist Sophie Neveu after a murder in the Louvre Museum in Paris entangles them in a dispute between the Priory of Sion and Opus Dei over the possibility of Jesus and Mary Magdalene having had a child together."}, 
    {id: 19, title: "The Bounre Identity", author: "Robert Ludlum", year: 1980, price: 4.89, sold: 9087, category: 6, image_url: "Images/The-bourne-identity.jpg", description:"“The Bourne Identity” is a gripping spy thriller written by Robert Ludlum. The story centers around Jason Bourne, a man who wakes up with amnesia and no memory of his past."}, 
    {id: 20, title: "The Three Musketeers", author: "Alexandre Dumas père", year: 1844, price: 2.67, sold: 8794, category: 7, image_url: "Images/The-three-musketeers.jpg", description:"This delightful, swashbuckling adventure follows the story of young D'Artagnan as he pursues his dream of becoming a musketeer"},
    {id: 21, title: "The Scarlet Pimpernel", author: "Baroness Emmuska Orczy", year: 1905, price: 3.23, sold: 6847, category: 7, image_url: "Images/The-scarlet-pimpernel.jpg", description:"Armed with only his wits and his cunning, one man recklessly defies the French revolutionaries and rescues scores of innocent men, women, and children from the deadly guillotine."}, 
    {id: 22, title: "Pillars of the Earth", author: "Ken Follett", year: 1989, price: 4.89, sold: 4726, category: 7, image_url: "Images/Pillars-of-the-earth.jpg", description:"The Pillars of the Earth tells the story of Philip, prior of Kingsbridge, a devout and resourceful monk driven to build the greatest Gothic cathedral the world has known ... of Tom, the mason who becomes his architect—a man divided in his soul ... of the beautiful, elusive Lady Aliena, haunted by a secret shame ... and of a struggle between good and evil that will turn church against state and brother against brother."}, 
    {id: 23, title: "The Hobbit", author: "J.R.R. Tolkien", year: 1937, price: 4.54, sold: 5837, category: 8, image_url: "Images/The-hobbit.jpg", description:"The Hobbit is set in Middle-earth and follows home-loving Bilbo Baggins, the hobbit of the title, who joins the wizard Gandalf and the thirteen dwarves of Thorin's Company, on a quest to reclaim the dwarves' home and treasure from the dragon Smaug."}, 
    {id: 24, title: "The Cavalier", author: "Jason L. McWhirter", year: 2012, price: 9.85, sold: 4238, category: 8, image_url: "Images/The-cavalier.jpg", description:"Burdened with the deaths of the unavenged and the chance of losing his own life, Velamir must decide if revenge is worth the cost."}, 
    {id: 25, title: "The Eye of the World", author: "Robert Jordan", year: 1990, price: 5.60, sold: 3498, category: 8, image_url: "Images/The-eye-of-the-world.jpg", description:"The book follows Moiraine Damodred as she arrives in Emond's Field on a quest to find the one prophesized to stand against The Dark One."}, 
    {id: 26, title: "Life of Pi", author: "Yann Martel", year: 2001, price: 8.45, sold: 8768, category: 9, image_url: "Images/Life-of-pi.jpg", description:"The fantasy novel revolves around a teenage Indian boy, Pi, who becomes lost at sea after a shipwreck. Pi finds himself struggling for survival against the torrential ocean with his only companion, a Bengal tiger."}, 
    {id: 27, title: "Into the Wild", author: "Jon Krakauer", year: 1996, price: 3.21, sold: 9327, category: 9, image_url: "Images/Into-the-wild.jpg", description:"Into the Wild follows a young man named Chris McCandless who escapes into nature in the pursuit of solitude."}, 
    {id: 28, title: "Into the Sunken City", author: "Dinesh Thiru", year: 2024, price: 4.67, sold: 2868, category: 10, image_url: "Images/Into-the-sunken-city.jpg", description:"Jin is 18 years old and the guardian of her 14-year-old sister, Thara. She lives in a lot of fear after her father's death in a diving accident and fights constantly with rebellious Thara. Eventually she finds her bravery and allows Thara room to grow."},
    {id: 29, title: "Spartan Gold", author: "", year: 2009, price: 9.12, sold: 265, category: 10, image_url: "Images/Spartan-gold.jpg", description:"Treasure-hunting husband-and-wife team Sam and Remi Fargo are exploring the Great Pocomoke Swamp in Maryland when they are shocked to discover a World War II German U-boat."},
    {id: 30, title: "Lost Empire", author: "", year: 2010, price: 11.29, sold: 503, category: 10, image_url: "Images/Lost-empire.jpg", description:"While scuba diving in Tanzania, Sam and Remi Fargo come upon a relic belonging to a long-lost Confederate ship. An anomaly about the relic sets them off chasing a mystery—but unknown to them, a much more powerful force is engaged in the same chase."},
    ];

//Normally data is stored in DB, when app sends a request to DB, it return this array of data
let categories = [ 
    {id: 1, category: "Space Opera"},
	{id: 2, category: "Dystopian"},
	{id: 3, category: "Cyberpunk"},
	{id: 4, category: "Timetravel"},
    {id: 5, category: "Alien Invasion"},
    {id: 6, category: "Action Adventure"},
    {id: 7, category: "Historical Adventure"},
    {id: 8, category: "Fantasy Adventure"},
    {id: 9, category: "Survival Stories"},
    {id: 10, category: "Treasure Hunts"},
];
        
//Normally data is stored in DB, when app sends a request to DB, it return this array of data
//Link: https://www.imdb.com/chart/top/
let votes =[{id: 1, like: 1345, dislike: 10},
    {id: 2, like: 5432, dislike: 11},
    {id: 3, like: 7895, dislike: 15},
    {id: 4, like: 9287, dislike: 3},
    {id: 5, like: 9978, dislike: 2},
    {id: 6, like: 19002, dislike: 0},
    {id: 7, like: 2020, dislike: 16},
    {id: 8, like: 5432, dislike: 11},
    {id: 9, like: 7895, dislike: 15},
    {id: 10, like: 9287, dislike: 3},
    {id: 11, like: 1345, dislike: 10},
    {id: 12, like: 5432, dislike: 11},
    {id: 13, like: 7895, dislike: 15},
    {id: 14, like: 9287, dislike: 3},
    {id: 15, like: 9978, dislike: 2},
    {id: 16, like: 19002, dislike: 0},
    {id: 17, like: 2020, dislike: 16},
    {id: 18, like: 5432, dislike: 11},
    {id: 19, like: 7895, dislike: 15},
    {id: 20, like: 9287, dislike: 3},
    {id: 21, like: 1345, dislike: 10},
    {id: 22, like: 5432, dislike: 11},
    {id: 23, like: 7895, dislike: 15},
    {id: 24, like: 9287, dislike: 3},
    {id: 25, like: 9978, dislike: 2},
    {id: 26, like: 19002, dislike: 0},
    {id: 27, like: 2020, dislike: 16},
    {id: 28, like: 5432, dislike: 11},
    {id: 29, like: 7895, dislike: 15},
    {id: 30, like: 9287, dislike: 3},
    
    
];

//Normally data is stored in DB, when app sends a request to DB, it return this array of data
//Link: https://www.imdb.com/chart/top/
let comments =[ {id: 1, comments: [{user: "John", comment:"Good Book"}, {user: "Ian", comment:"Not bad"},{user: "Daniel", comment:"Recommended"}]},
    {id: 2, comments: [{user: "Graham", comment:"Great Book"}, {user: "Noor", comment:"Very interesting"},{user: "Kim", comment:"Excellent Book"}]},
    {id: 3, comments: [{user: "John", comment:"Good Book"}, {user: "Ian", comment:"Not bad"},{user: "Daniel", comment:"Recommended"}]},
    {id: 4, comments: [{user: "Graham", comment:"Great Book"}]},
    {id: 5, comments: [{user: "Ian", comment:"Not bad"},{user: "Daniel", comment:"Recommended"}]},
    {id: 6, comments: [{user: "Kim", comment:"Excellent Book"}]},
    {id: 7, comments: [ {user: "Ian", comment:"Must read"},{user: "Daniel", comment:"Recommended"}]},
    {id: 8, comments: [{user: "Noor", comment:"Very interesting"}]},
    {id: 9, comments: [{user: "John", comment:"Good Book"}, {user: "Ian", comment:"Not bad"},{user: "Daniel", comment:"Recommended"}]},
    {id: 10, comments: [{user: "Graham", comment:"Great Book"}, {user: "Noor", comment:"Very interesting"},{user: "Kim", comment:"Excellent Book"}]},
    {id: 11, comments: [{user: "John", comment:"Good Book"}, {user: "Ian", comment:"Not bad"},{user: "Daniel", comment:"Recommended"}]},
    {id: 12, comments: [{user: "Graham", comment:"Great Book"}]},
    {id: 13, comments: [{user: "Ian", comment:"Not bad"},{user: "Daniel", comment:"Recommended"}]},
    {id: 14, comments: [{user: "Kim", comment:"Excellent Book"}]},
    {id: 15, comments: [ {user: "Ian", comment:"Must watch"},{user: "Daniel", comment:"Recommended"}]},
    {id: 16, comments: [{user: "Noor", comment:"Very interesting"}]},
    {id: 17, comments: [{user: "John", comment:"Good Book"}]},
    {id: 18, comments: [{user: "Noor", comment:"Great Book, recommended"},{user: "Kim", comment:"Excellent Book"}]},
    {id: 19, comments: [{user: "John", comment:"Good Book"}, {user: "Ian", comment:"Not bad"},{user: "Daniel", comment:"Recommended"}]},
    {id: 20, comments: [{user: "Noor", comment:"Very interesting"},{user: "Kim", comment:"Excellent movie"}]},
    {id: 21, comments: [{user: "John", comment:"Good Book"}, {user: "Ian", comment:"Not bad"},{user: "Daniel", comment:"Recommended"}]},
    {id: 22, comments: [ {user: "Noor", comment:"Very interesting"},{user: "Kim", comment:"Excellent Book"}, {user: "Graham", comment:"Great Book"}]},
    {id: 23, comments: [{user: "John", comment:"Good Book"}, {user: "Ian", comment:"Not bad"},{user: "Daniel", comment:"Recommended"}]},
    {id: 24, comments: [{user: "Kim", comment:"Excellent Book"}, {user: "Graham", comment:"Great Book"}, {user: "Noor", comment:"Very interesting"}]},
    {id: 25, comments: [{user: "Ian", comment:"Not bad"},{user: "Daniel", comment:"Recommended"}]},
    {id: 26, comments: [{user: "Kim", comment:"Excellent Book"}]},
    {id: 27, comments: [ {user: "Ian", comment:"Must watch"},{user: "Daniel", comment:"Recommended"}]},
    {id: 28, comments: [{user: "Noor", comment:"Very interesting"}]},
    {id: 29, comments: [{user: "John", comment:"Good Book"}, {user: "Ian", comment:"Not bad"},{user: "Daniel", comment:"Recommended"}]},
    {id: 30, comments: [{user: "Graham", comment:"Great Book"}, {user: "Noor", comment:"Very interesting"},{user: "Kim", comment:"Excellent Book"}]}
];     